spring:
  # DataSource ?? : DB ? H2 ??? ???? ??.
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/kt-test
    username: sa
    password:

  # H2 ??
  h2:
    console:
      enabled: true # ?? ?? false
      path: /db_console

  # JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true # JPA ?? ?? ??? ??
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.format_sql: false